# -*- coding: utf-8 -*-
"""Praktikum6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QGYD5V2DG_Y1lg_KEcWO3xzjAachObro
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from mpl_toolkits.mplot3d import Axes3D

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('../content/drive/MyDrive/Praktikum Machine Learning_Amaya Eshia_0110224102_Ai02/Praktikum 5/Data/Iris.csv')
df

df.describe()

df.info()

df["Species"].unique()

df["Species"].value_counts()

"""Feature Selection"""

X = df[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']]

# kolom target (label)
Y = df['Species']

X.head()

Y.head()

"""Splitting Data"""

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

"""Buat Model"""

# membuat model SVM dengan kernel linear
model = SVC(kernel='rbf')

model.fit(X_train, Y_train)

"""Evaluasi Model"""

Y_pred = model.predict(X_test)

# Akurasi
print(f"Akurasi: {accuracy_score(Y_test, Y_pred) * 100:.2f}%")

#Laporan Klasifikasi
print("\nLaporan Klasifikasi:\n", classification_report(Y_test, Y_pred))

"""Data Visualization"""

from os import confstr
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
import seaborn as sns

print(":\nConfusion Matrix:\n", confusion_matrix(Y_test, Y_pred))

# Buat confusion matrix
cm = confusion_matrix(Y_test, Y_pred)

plt.figure(figsize=(6, 4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title('Confusion Matrix')
plt.xlabel('Predicted Labels')
plt.ylabel('True Labels')
plt.show()

import matplotlib.pyplot as plt

plt.scatter(df['SepalLengthCm'], df['SepalWidthCm'], c=df['Species'].astype('category').cat.codes)
plt.xlabel('Sepal Length (cm)')
plt.ylabel('Sepal Width (cm)')
plt.title('Visualisasi Klasifikasi Iris')
plt.show

le = LabelEncoder()
Y_test_encoded = le.fit_transform(Y_test)
Y_pred_encoded = le.transform(Y_pred)

plt.figure(figsize=(8, 6))

plt.scatter(X_test['SepalLengthCm'], X_test['SepalWidthCm'],
            c=Y_test_encoded, cmap='viridis', marker='o', label='True Labels',alpha=0.6)
plt.scatter(X_test['SepalLengthCm'], X_test['SepalWidthCm'],
            c=Y_pred_encoded, cmap='viridis', marker='x', label='Predicted Labels', alpha=0.6)

plt.title('Scatter Plot: True vs Predicted Labels (Sepal Length vs Sepal Width)')
plt.xlabel('Sepal Length (cm)')
plt.ylabel('Sepal Width (cm)')
plt.legend()
plt.show ()

le = LabelEncoder()
df['SpeciesEncoded'] = le.fit_transform(df['Species'])

# warna untuk tiap kelas

colors = ['r', 'g', 'b']
labels = le.classes_

fig = plt.figure(figsize=(18, 7))
axl = fig.add_subplot(121, projection='3d')
for i, species in enumerate(labels):
  subset = df[df['SpeciesEncoded'] == i]
  axl.scatter(
      subset['SepalLengthCm'],
      subset['PetalLengthCm'],
      subset['PetalWidthCm'],
      color=colors[i],
      label=species,
      s=50
  )
axl.set_title('Label Asli')
axl.set_xlabel('Sepal Length (cm)')
axl.set_ylabel('Petal Length (cm)')
axl.set_zlabel('Petal Width (cm)')
axl.legend()

# Plot 2: Label Prediksi
ax2 = fig.add_subplot(122, projection='3d')
df['Predicted'] = None
df.loc[X_test.index, 'Predicted'] = Y_pred

# Encode predicted labels for plotting
predicted_encoded = le.transform(df.loc[X_test.index.dropna(), 'Predicted'])
df.loc[X_test.index.dropna(), 'PredictedEncoded'] = predicted_encoded

for i, species_label in enumerate(labels):
  subset = df.loc[X_test.index].dropna(subset=['PredictedEncoded'])
  subset = subset[subset['PredictedEncoded'] == i]

  ax2.scatter(
      subset['SepalLengthCm'],
      subset['PetalWidthCm'],
      subset['PetalLengthCm'],
      color=colors[i],
      label=f"Predicted: {species_label}",
      s=50,
      alpha=0.7
  )

  ax2.set_title('Label Prediksi (test set)')
  ax2.set_xlabel('Sepal Length Cm')
  ax2.set_ylabel('Petal Length Cm')
  ax2.set_zlabel('Petal Width Cm')
  ax2.legend()

plt.show()