# -*- coding: utf-8 -*-
"""TugasMandiri6(2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10KJilUjOIBEkci4eKR8x21jZywv_xX8k
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

# Ganti path ini dengan lokasi heart.csv di drive Anda jika berbeda
df = pd.read_csv('/content/drive/MyDrive/Praktikum Machine Learning_Amaya Eshia_0110224102_Ai02/Praktikum 6/Data/heart.csv')  # Asumsi path serupa dengan Iris.csv
df

df.info()

df.describe()

df.isnull().sum()

df.duplicated().sum()

df = df.drop_duplicates()
df.duplicated().sum()

df["target"].value_counts()

df["target"].value_counts(normalize=True) * 100

# Cek unique values pada kolom target (seperti df["Species"].unique())
print("Unique values di kolom 'target':")
df["target"].unique()

# Cek distribusi kelas (seperti df["Species"].value_counts())
print("Distribusi kelas pada kolom 'target':")
df["target"].value_counts()

# Feature Selection (seperti di screenshot)
X = df[['age', 'trestbps', 'chol', 'thalach', 'oldpeak']]  # Pilih 5 fitur contoh
# Atau gunakan semua fitur kecuali target:
# X = df.drop('target', axis=1)

y = df['target']  # Kolom target

X = df.drop('target', axis=1)  # Fitur
y = df['target']  # Target (0 atau 1 untuk penyakit jantung)

# Split data menjadi train dan test (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X.head()

# Inisialisasi model SVM dengan kernel linear (bisa diganti ke 'rbf', 'poly', dll.)
model = SVC(kernel='linear', random_state=42)

# Train model
model.fit(X_train, y_train)

# Prediksi pada data test
y_pred = model.predict(X_test)

# Evaluasi model
accuracy = accuracy_score(y_test, y_pred)
print(f'Akuracy: {accuracy * 100:.2f}%')

print('Classification Report:')
print(classification_report(y_test, y_pred))

print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))

# Gunakan scaling (penting untuk SVM!)
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = SVC(kernel='rbf', C=1.0, random_state=42)
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

# --- BAGIAN CONFUSION MATRIX (SESUAI SCREENSHOT) ---

# Hitung confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Tampilkan dalam bentuk teks
print("Confusion Matrix:")
print(cm)

# Visualisasi dengan seaborn heatmap
plt.figure(figsize=(6, 4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title('Confusion Matrix')
plt.xlabel('Predicted Labels')
plt.ylabel('True Labels')
plt.show()

plt.figure(figsize=(8, 6))

# Scatter plot: x = age, y = thalach, warna berdasarkan target
plt.scatter(df['age'], df['thalach'],
            c=df['target'],           # Warna berdasarkan target (0 atau 1)
            cmap='coolwarm',          # Biru = 0, Merah = 1
            alpha=0.8,
            edgecolors='k')

# Label dan judul
plt.xlabel('Age (tahun)')
plt.ylabel('Thalach (detak jantung maksimum)')
plt.title('Visualisasi Klasifikasi Penyakit Jantung')

# Tambahkan colorbar
cbar = plt.colorbar()
cbar.set_label('Target: 0 = Tidak Sakit, 1 = Sakit Jantung')

plt.grid(True, alpha=0.3)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# Load the data from heart.csv
df = pd.read_csv('/content/drive/MyDrive/Praktikum Machine Learning_Amaya Eshia_0110224102_Ai02/Praktikum 6/Data/heart.csv')  # Asumsi path serupa dengan Iris.csv
df

# Features and target
X = df.drop('target', axis=1)
y = df['target']

# Split into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a simple logistic regression model
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

# Predict on test set
y_pred = model.predict(X_test)

# Plot similar to the example, using 'age' and 'chol' as features
plt.figure(figsize=(8, 6))
plt.scatter(X_test['age'], X_test['chol'], c=y_test, cmap='viridis', marker='o', label='True Labels', alpha=0.6)
plt.scatter(X_test['age'], X_test['chol'], c=y_pred, cmap='viridis', marker='x', label='Predicted Labels', alpha=0.6)
plt.title('Scatter Plot: True vs Predicted Labels (Age vs Cholesterol)')
plt.xlabel('Age')
plt.ylabel('Cholesterol')
plt.legend()
plt.show()

# Visualisasi 3D sederhana: Pilih 3 fitur utama untuk plot (misalnya age, chol, thalach)
# Ini hanya contoh, karena dataset punya banyak fitur
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

# Plot data berdasarkan target
ax.scatter(df['age'], df['chol'], df['thalach'], c=df['target'], cmap='viridis')

ax.set_xlabel('Age')
ax.set_ylabel('Chol')
ax.set_zlabel('Thalach')
plt.show()

