# -*- coding: utf-8 -*-
"""Salinan dari Praktikum1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H5Qu1bomnEg2qXiQrTysh6hSfWvtUXPG
"""

pip install pandas

from google.colab import drive
drive.mount('/content/drive')



file_path = '/content/drive/MyDrive/'

import os

# Contoh cek isi folder 'My Drive' setelah di-mount
folder_path = '/content/drive/MyDrive/Praktikum 1/Data/'

files_and_folders = os.listdir(folder_path)
print(files_and_folders)

import pandas as pd

df=pd.read_csv(folder_path +'/day.csv')
df.head()

df.tail()

df.info()

df1 = df[['instant', 'dteday', 'season', 'temp', 'hum', 'windspeed']]

print(df1.head())

os.makedirs('data', exist_ok=True)
df1.to_csv('data/latihan01.csv', index=False)
