# -*- coding: utf-8 -*-
"""Praktikum1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J435113b6H8Vraqu3loHezxjqx9Lb19S
"""

pip install pandas

from google.colab import drive
drive.mount('/content/drive')



file_path = '/content/drive/MyDrive/'

import os

# Contoh cek isi folder 'My Drive' setelah di-mount
folder_path = '/content/drive/MyDrive/Praktikum 1/Data/'

files_and_folders = os.listdir(folder_path)
print(files_and_folders)

import pandas as pd

df=pd.read_csv(folder_path +'/day.csv')
df.head()

df.tail()

df.info()