# -*- coding: utf-8 -*-
"""Praktikum9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gistfhE8r9EUK_oA2YRR47qjkGZcqjkB
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

from google.colab import drive
drive.mount('/content/drive')

# With link
titanic_data = pd.read_csv('https://drive.google.com/uc?export=download&id=1w5_b7k2L3vi9MpvVoS-LXX7gRU6k_zY-')

titanic_data.head()

titanic_data[9:12]

titanic_data.tail(9)

titanic_data.shape

titanic_data.info()

titanic_data.isnull().sum()

"""Handling the missing"""

# Menghapus kolom
titanic_data = titanic_data.drop(columns=['PassengerId', 'Cabin', 'Name', 'Ticket'], axis=1)

titanic_data['Age'].fillna(titanic_data['Age'].median(), inplace=True)
titanic_data['Fare'].fillna(titanic_data['Fare'].median(), inplace=True)

titanic_data.boxplot(column=['Age'])
plt.title("Boxplot of Age with outliers")
plt.show()

titanic_data.describe(include='all')

titanic_data['Survived'].value_counts()

titanic_data['Sex'].value_counts()

fig, axes = plt.subplots(nrows=2, ncols=3, figsize=(20, 15))

axes = axes.flatten()

sns.countplot(x='Survived', data=titanic_data, ax=axes[0])
axes[0].set_title('Survived')

sns.countplot(x='Sex', data=titanic_data, ax=axes[1])
axes[1].set_title('Sex')

sns.countplot(x='Pclass', data=titanic_data, ax=axes[2])
axes[2].set_title('Pclass')

sns.countplot(x='Sex', hue='Survived', data=titanic_data, ax=axes[3])
axes[3].set_title('Survival of Sex')

sns.countplot(x='Pclass', hue="Survived", data=titanic_data, ax=axes[4])
axes[4].set_title('Survival of Pclass')

sns.countplot(x='Embarked', hue='Survived', data=titanic_data, ax=axes[5])
axes[5].set_title('Survival of Pclass')

plt.tight_layout()
plt.show()

replacement = {
    'Sex': {'male': 1, 'female': 0},
    'Embarked': {'S': 0, 'C': 1, 'Q': 2}
}

titanic_data.replace(replacement, inplace=True)

titanic_data.iloc[0:9]

X = titanic_data