# -*- coding: utf-8 -*-
"""Praktikum02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HnLHwEOcB6QJkrnoClbMk4a3shikcJ4e
"""

# menghubungkan colab dengan google drive
from google.colab import drive
drive.mount('/content/drive')

# memanggil data set lewat gdrive
path = "/content/drive/MyDrive/Praktikum Machine Learning_Amaya Eshia_0110224102_Ai02/Praktikum ML 2"

# membaca file csv menggunakan pandas
import pandas as pd
df = pd.read_csv(path + "/Data/500_Person_Gender_Height_Weight_Index.csv")

# Mencari info data pada file (tips datanya, not nul count data, nama kolom)
df.info()

# Menghitung mean semua kolom numerik
df['Height'].mean()

# Menghitung median semua kolom numerik
df['Height'].median()

# Menghitung modus (hati-hati karena bisa lebih dari satu)
df['Height'].mode()

# Menghitung Variansi & Standard Deviasi
df.var(numeric_only=True)

# Menghitung Standar Deviasi
df.std(numeric_only=True)

# Hitung kuartil pertama (Q1)
q1 = df['Height'].quantile(0.25)
print("Q1 : ", q1)

# Hitung kuartil ketiga (Q3)
q3 = df['Height'].quantile(0.75)
print("Q3 : ", q3)

# Hitung IQR (Interquartile Range)
iqr = q3 - q1
print("IQR : ", iqr)

# Untuk membuat statistika deskripsi pada type data int
df.describe()

# Menghitung matriks korelasi untuk semua kolom numerik
correlation_matrix = df.corr(numeric_only=True)

# Menampilkan matriks korelasi
print("Matriks Korelasi:")
print(correlation_matrix)

"""Bagian 1 : BOXPLOT"""

import pandas as pd
import numpy as np

df.boxplot(column=['Height', 'Weight'])

"""Bagian 2 : Histogram"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Ambil data Height
data_height = df["Height"]

# Buat histogram
n, bins, patches = plt.hist(data_height, bins=5, color='pink', edgecolor='black')

# Tambahkan label
plt.title('Histogram Nilai')
plt.xlabel('Height')
plt.ylabel('Frekuensi')

# Tampilkan rentang frekuensi di sumbu x
bin_centers = 0.5 * (bins[:-1] + bins[1:])
plt.xticks(bin_centers, ['{:.0f}-{:.0f}'.format(bins[i], bins[i+1]) for i in range(len(bins)-1)])

# Tampilkan histogram
plt.show()

"""Bagian 3 : Scatter Plot"""

import pandas as pd
import matplotlib.pyplot as plt

# Buat DataFrame contoh
data = {
    'Nilai1': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Nilai2': [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
}

df2 = pd.DataFrame(data)

# Buat scatter plot
plt.scatter(df2['Nilai1'], df2['Nilai2'], color='blue', marker='o')

# Tambahkan label
plt.title('Scatter Plot Korelasi Positif')
plt.xlabel('Nilai1')
plt.ylabel('Nilai2')

# Tambahkan grid
plt.grid(True)

# Tampilkan plot
plt.show()

"""Scotter Negatif :"""

import pandas as pd
import matplotlib.pyplot as plt

# Buat DataFrame contoh
data = {
    'Nilai1': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Nilai2': [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
}

df3 = pd.DataFrame(data)

# Buat scatter plot
plt.scatter(df3['Nilai1'], df3['Nilai2'], color='red', marker='x')

# Tambahkan label
plt.title('Scatter Plot Korelasi Negatif')
plt.xlabel('Nilai1')
plt.ylabel('Nilai2')

# Tambahkan grid
plt.grid(True)

# Tampilkan plot
plt.show()