# -*- coding: utf-8 -*-
"""TugasMandiri12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kepjUeHiMSGDWCCkl-GdRzBCeqhk4p82

Amaya Eshia - 0110224102 - AI_02 _ Machine Learning - TugasMandiri12
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import DBSCAN

from google.colab import drive
drive.mount('/content/gdrive')

path = "/content/gdrive/MyDrive/Praktikum Machine Learning_Amaya Eshia_0110224102_Ai02/Praktikum 12/data/AB_NYC_2019.csv"

"""Load Dataset"""

try:

    path = "/content/AB_NYC_2019.csv"
    df = pd.read_csv(path)
    print("Berhasil load data!")
except FileNotFoundError:
    print("Error: File tidak ditemukan. Upload dulu file csv-nya.")

df_clean = df[(df['price'] < 500)].copy()
X = df_clean[['latitude', 'longitude']]

print("=== 5 Baris Data Koordinat ===")
print(X.head())
print(f"\nTotal Data: {len(X)}")

df = pd.read_csv(path)
print(df.head())

print(df.info())
print("\nJumlah Missing Values:")
print(df.isnull().sum())

coords = df[['latitude', 'longitude']]
print("\nData Koordinat:")
print(coords.head())

"""Visualisasi Awal"""

import folium
from folium.plugins import HeatMap

map_data = df_clean[['latitude', 'longitude']].values.tolist()

# Tentukan titik tengah peta (rata-rata lokasi)
center_lat = df_clean['latitude'].mean()
center_long = df_clean['longitude'].mean()

m = folium.Map(location=[center_lat, center_long], zoom_start=11)

HeatMap(map_data, radius=13, blur=15, min_opacity=0.4).add_to(m)

# --- Tampilkan Peta ---
print("Peta Heatmap Kepadatan Airbnb (Merah = Sangat Padat)")
m

"""Mencari Nilai Epsilon Optimal dengan Metode ELBOW"""

from sklearn.neighbors import NearestNeighbors

# Konversi ke Radians untuk perhitungan jarak bumi
x = X # Define x with the coordinate data
x_rad = np.radians(x)

k = 20
nbrs = NearestNeighbors(n_neighbors=k, metric='haversine').fit(x_rad)
distances, indices = nbrs.kneighbors(x_rad)

# Ambil jarak ke tetangga ke-k dan urutkan
distance_kth = distances[:, k-1]
distance_kth_sorted = np.sort(distance_kth)

# Plot K-Distance Graph (Elbow Method)
plt.figure(figsize=(10, 5))
plt.plot(distance_kth_sorted)
plt.title(f'K-Distance Graph (Elbow Method) untuk k={k}')
plt.ylabel('Jarak Epsilon (Radians)')
plt.xlabel('Data Points')
plt.grid(True)
plt.show()

"""Modeling DBSCan"""

# Parameter Bumi
kms_per_radian = 6371.0088
eps_km = 0.2  # Radius cluster 200 meter
eps_rad = eps_km / kms_per_radian # Konversi ke radian

print(f"Running DBSCAN dengan radius {eps_km} km...")
db = DBSCAN(eps=eps_rad, min_samples=20, metric='haversine', algorithm='ball_tree')
db.fit(x_rad)

# Simpan hasil label ke dataframe
df_clean['cluster'] = db.labels_

# Cek sebaran cluster
print("\n=== Hasil Clustering ===")
print(df_clean['cluster'].value_counts().head(10))
print(f"\nJumlah Cluster Terbentuk: {len(set(db.labels_)) - 1}")
print(f"Jumlah Noise (Outlier): {list(db.labels_).count(-1)}")

"""Evaluasi Model"""

from sklearn.utils import resample
from sklearn.metrics import silhouette_score

X_sample, label_sample = resample(x_rad, db.labels_, n_samples=5000, random_state=42)

# Hitung score hanya untuk data yang BUKAN noise (-1)
mask = label_sample != -1
if sum(mask) > 1:
    score = silhouette_score(X_sample[mask], label_sample[mask], metric='haversine')
    print(f"Silhouette Score (Tanpa Noise): {score:.4f}")
else:
    print("Semua data dianggap noise, sesuaikan parameter eps!")

"""Latest Visualization"""

# Visualisasi Scatter Plot (Peta)
plt.figure(figsize=(12, 8))

# Plot Noise (Warna Abu-abu)
noise = df_clean[df_clean['cluster'] == -1]
plt.scatter(noise['longitude'], noise['latitude'], s=3, c='lightgrey', label='Noise', alpha=0.5)

# Plot Cluster (Warna-warni)
clustered = df_clean[df_clean['cluster'] != -1]
plt.scatter(clustered['longitude'], clustered['latitude'], c=clustered['cluster'], s=5, cmap='tab20', label='Cluster', alpha=0.8)

plt.title(f'Peta Persebaran Cluster Airbnb (Radius {eps_km*1000} meter)')
plt.xlabel('Longitude')
plt.ylabel('Latitude')
plt.axis('equal') # Agar proporsi peta benar
plt.legend(markerscale=3)
plt.show()