# -*- coding: utf-8 -*-
"""Praktikum7_DataSatelit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bKGnhqGQt3c0TFp-uqOh0KojsT7nh991

# **Amaya Eshia - 0110224102 - 24TI06 - AI02**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

"""# ***# Load Data***"""

# menghubungkan colab dengan google drive
from google.colab import drive
drive.mount('/content/drive')

# MEmanggil dataset via gdrive
path = "/content/drive/MyDrive/Praktikum Machine Learning_Amaya Eshia_0110224102_Ai02/Praktikum 7 (Review)/Data/dataset_satelit.csv"

df = pd.read_csv('/content/drive/MyDrive/Praktikum Machine Learning_Amaya Eshia_0110224102_Ai02/Praktikum 7 (Review)/Data/dataset_satelit.csv')
df.head()

df.info()

df.describe()

df.columns

# Ubah kolom Mg ke float

df['Mg'] = pd.to_numeric(df['Mg'], errors='coerce')

# Hilangkan baris yang ada missing value
df = df.dropna()

"""# ***Feature Selection***"""

# x = df[['b2','b3','b4','b8','b11','Sigma_VV','Sigma_VH']]
# y = df['N']

x = df[['P', 'K', 'Ca', 'Mg', 'Fe', 'Mn',
       'Cu', 'Zn', 'B', 'b12', 'b11', 'b9', 'b8a', 'b8', 'b7', 'b6', 'b5',
       'b4', 'b3', 'b2', 'b1', 'Sigma_VV', 'Sigma_VH', 'plia', 'lia', 'iafe',
       'gamma0_vv', 'gamma0_vh', 'beta0_vv', 'beta0_vh']]

y = df['N']

"""# ***Splitting Data***"""

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(x_train, y_train)

"""# ***MACHINE***"""

# Testing
y_pred = model.predict(x_test)

# EValuasi Model
r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

print("R2 Score :", r2)
print("RMSE :", mse)

coeff = pd.DataFrame({
    'Fitur' : x.columns,
    'Koefisien' : model.coef_
})

print(coeff)

import statsmodels.api as sm

x_sm = sm.add_constant(x)
model_ols = sm.OLS(y, x_sm).fit()
print(model_ols.summary())

import matplotlib.pyplot as plt

print("\nVisualisasi Hasil Model")

# 1. Scatter plot: Actual vs Predicted
plt.figure(figsize=(10, 6))
# Plot titik-titik data (aktual vs prediksi)
sns.scatterplot(x=y_test, y=y_pred)
# Plot garis diagonal merah (x=y) sebagai referensi
# Jika titik-titik mendekati garis ini, prediksinya bagus
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)
plt.title('Actual vs Predicted Values (Data Test)')
plt.xlabel('Actual N')
plt.ylabel('Predicted N')
plt.grid(True)
plt.show()

# Analisis Residual (pada Data Training)
# Kita perlu prediksi pada data training untuk analisis residual
y_train_pred = model.predict(x_train)
residuals = y_train - y_train_pred

print("\n Analisis Residual (pada Data Training)")

# Plot Residuals vs Predicted
# Cek asumsi Homoskedastisitas (varian error konstan)
plt.figure(figsize=(10, 6))
sns.scatterplot(x=y_train_pred, y=residuals)
plt.axhline(0, color='red', linestyle='--') # Garis horizontal di y=0
plt.title('Residuals vs Predicted Values')
plt.xlabel('Predicted N (Training)')
plt.ylabel('Residuals')
plt.grid(True)
plt.show()

# Histogram Residuals
# Mengecek asumsi Normalitas (error terdistribusi normal)
plt.figure(figsize=(10, 6))
sns.histplot(residuals, kde=True)
plt.title('Histogram of Residuals')
plt.xlabel('Residual')
plt.ylabel('Frequency')
plt.grid(True)
plt.show()